---
- src: https://gitlab.com/ansible-opletal/ansible-workstation/ansible-role-packages.git
  scm: git
  version: master

- src: https://git.sr.ht/~fourstepper/ansible-role-configuration
  scm: git
  version: master

- src: https://git.sr.ht/~fourstepper/ansible-role-logiops
  scm: git
  version: master

- src: https://gitlab.com/ansible-opletal/ansible-workstation/ansible-role-sway.git
  scm: git
  version: master

- src: https://git.sr.ht/~fourstepper/ansible-role-alacritty
  scm: git
  version: master

- src: https://gitlab.com/ansible-opletal/ansible-workstation/ansible-role-ranger.git
  scm: git
  version: master

- src: https://gitlab.com/ansible-opletal/ansible-workstation/ansible-role-neovim.git
  scm: git
  version: master

- src: https://gitlab.com/ansible-opletal/ansible-workstation/ansible-role-tmux.git
  scm: git
  version: master

- src: https://git.sr.ht/~fourstepper/ansible-role-fonts
  scm: git
  version: master

- src: https://gitlab.com/ansible-opletal/ansible-role-terminal.git
  scm: git
  version: master

- src: https://git.sr.ht/~fourstepper/ansible-role-browserpass
  scm: git
  version: master

- src: https://git.sr.ht/~fourstepper/ansible-role-aerc
  scm: git
  version: master

- src: https://gitlab.com/ansible-opletal/ansible-workstation/ansible-role-org.git
  scm: git
  version: master
