---
- src: https://github.com/fourstepper/ansible-role-packages
  scm: git
  version: main

- src: https://github.com/fourstepper/ansible-role-logiops
  scm: git
  version: main

- src: geerlingguy.docker
