---
- hosts: all

  pre_tasks:
    - name: Include the distribution vars
      include_vars: "vars/{{ ansible_facts['distribution'] }}.yml"

    - name: Run whoami to get the user name
      command: whoami
      changed_when: false
      register: whoami

    - name: Set a fact with the user name.
      set_fact:
        ansible_user: "{{ whoami.stdout }}"

    - name: Install python3-apt
      package:
        name: python3-apt
        state: present
      become: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Configure the source directory for compilation
      file:
        path: "{{ src_dir }}"
        state: directory
        recurse: true
      when: src_dir is defined

    - name: Update cache for Debian-based distros
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false
      become: true

    - name: Update cache for Alpine
      apk:
        update_cache: yes
      when: ansible_facts['distribution'] == 'Alpine'
      changed_when: false
      become: true

    - name: Upgrade the system
      package:
        name: "*"
        state: latest
      become: true
      when: |
        upgrade is defined and upgrade and
        ansible_facts['distribution'] != 'Alpine'

    - name: Upgrade the system
      community.general.apk:
        available: yes
        upgrade: yes
      become: true
      when: |
        upgrade is defined and upgrade and
        ansible_facts['distribution'] == 'Alpine'

  roles:
    - role: ansible-role-packages
      when: install_packages|default(false)

    - role: ansible-role-aerc
      when: install_aerc|default(false)

    - role: ansible-role-browserpass
      when: install_browserpass|default(false)

    - role: ansible-role-sway
      when: install_sway|default(false)

    - role: ansible-role-org
      when: install_org|default(false)

    - role: ansible-role-tmux
      when: install_tmux|default(false)

    - role: ansible-role-alacritty
      when: install_alacritty|default(false)

    - role: ansible-role-fonts
      when: install_fonts|default(false)

    - role: ansible-role-neovim
      when: install_neovim|default(false)

    - role: ansible-role-configuration
      when: install_configuration|default(false)

    - role: ansible-role-logiops
      when: install_logiops|default(false) and ansible_facts['distribution'] != "Alpine"

    - role: ansible-role-shell
      when: install_terminal|default(false)

    - role: ansible-role-ranger
      when: install_ranger|default(false)

    - role: ansible-role-weechat
      when: install_weechat|default(false)

  tasks:
    - name: Upgrade the system
      package:
        name: "*"
        state: latest
      become: true
      when: |
        upgrade is defined and upgrade and
        ansible_facts['distribution'] != 'Alpine'

    - name: Upgrade the system
      community.general.apk:
        available: yes
        upgrade: yes
      become: true
      when: |
        upgrade is defined and upgrade and
        ansible_facts['distribution'] == 'Alpine'
