---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
driver:
  name: podman
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-fedora33}-ansible:latest"
    command: ""
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
