encryption_passphrase: "{{ borgmatic_encryption_passphrase }}"

source_directories:
    - '/home/*'

exclude_patterns:
    - '/home/*/.cache'
    - '/home/*/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common'

exclude_caches: true

repositories:
    - path: ssh://root@files.home.robinopletal.com/data/hdd/borg/desktop.borg
      label: nas
    - path: ssh://u375033-sub1@u375033.your-storagebox.de:23/./desktop.borg
      label: hetzner

ntfy:
  topic: "{{ borgmatic_ntfy_topic }}"
  fail:
    title: A borgmatic backup failed on {{ ansible_hostname }}
    message: You should probably fix it

keep_daily: 7
keep_weekly: 4
keep_monthly: 6
